### ISSUE TITLE
yaml文件需要更改

### ISSUE THREAD

**Issue by lyyilin** [FerretAngel/labelImage#2]
is:issue is:open 您好，我使用了您的在线标注，但是如果我自己添加了种类后，这个yaml文件需要更改，博主后续会考虑自动保存吗？

**Comment by FerretAngel** [comment]
不好意思，我没看懂你的描述。你是想说编辑分类之后没有自动保存吗？导致你下一次打开的时候依然是默认的 标签这样吗？
这个标签在任何更改后都会自动保存到本地localstorage里面，您可以在浏览器调试工具里面看到。

**Comment by lyyilin** [comment]
感谢您的回答，我没表达清楚，就是我在训练的时候 model.train(data="coco8.yaml", epochs=2, imgsz=640, batch = 1, workers = 16)，会用到"coco8.yaml"，但是我想要的标签不在这预设的80个种类里面，我想自己再添加几个类别，但是我添加后，没找到跟新后的yaml文件，我想表达的意思是，这个yaml文件也会更新，并保存到本地，便于训练。

**Comment by FerretAngel** [comment]
完整的yaml文件更新不太可能，因为浏览器因为安全原因无法获取到真实的地址。但是针对你这个分类数据的提议，可以增加一个按钮，一键导出分类数据。例如
```yaml
name:
 - bus
 - human
 - ...
 ```

**Comment by lyyilin** [comment]
嗯嗯，就是这个意思，如果博主能加上这个功能就太棒了！！！！！！

**Comment by FerretAngel** [comment]
已经更新了，刷新页面就能看到新增的导出按钮。感谢你的建议！
